In [2]:
import numpy as np
import pandas as pd

1. cctv 데이터를 다음과 같이 만들어 cctv.csv 파일에 저장하세요.

In [3]:
df = pd.read_csv('../data/서울시 자치구 년도별 CCTV 설치 현황_221231기준.csv', encoding='euc-kr', thousands=',')
df

,구분,총계,2013년 이전설치된 CCTV,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년,2022년
0,계,91341,2804,3097,3981,6576,8850,11566,11024,13151,11912,9144,9236
1,종로구,1980,36,540,107,161,131,158,152,69,250,85,291
2,중 구,2584,130,87,77,236,240,372,386,155,361,403,137
3,용산구,2847,44,50,68,83,295,491,115,322,623,422,334
4,성동구,4047,58,99,110,366,279,945,459,647,485,367,232
5,광진구,3480,507,82,84,64,21,465,443,709,172,662,271
6,동대문구,2759,1,4,12,107,802,711,201,218,223,221,259
7,중랑구,4193,224,331,104,145,153,170,215,1074,976,507,294
8,성북구,4842,137,170,229,322,594,811,867,714,253,407,338
9,강북구,3321,0,21,16,68,210,4,375,963,569,298,797
10,도봉구,2247,103,2,79,72,103,117,200,202,183,600,586
11,노원구,2617,77,153,75,510,329,172,216,326,387,220,152
12,은평구,4653,17,44,332,329,555,403,635,1057,288,471,522
13,서대문구,3445,312,144,127,77,254,524,389,344,587,207,480
14,마포구,2628,21,40,109,170,458,376,368,494,298,177,117
15,양천구,3851,197,139,128,239,422,563,830,311,337,338,347
16,강서구,3265,67,59,202,193,168,506,259,458,359,439,555
17,구로구,4693,37,361,193,269,353,563,545,794,651,684,243
18,금천구,2636,0,0,43,361,133,196,539,367,513,207,277
19,영등포구,4553,109,81,295,360,285,422,803,153,1357,329,359
20,동작구,2671,66,25,502,127,256,271,300,307,432,30,355
21,관악구,5398,362,244,302,537,607,676,662,890,404,550,164
22,서초구,4995,74,86,70,559,518,1054,426,344,422,566,876
23,강남구,7243,59,62,573,826,1295,989,744,790,923,514,468
24,송파구,3203,84,78,88,221,163,256,516,1081,224,139,353
25,강동구,3190,82,195,56,174,226,351,379,362,635,301,429

In [4]:
import warnings
warnings.filterwarnings('ignore')

df1 = df[1:]

df1 = df1.replace(',', '')
df2 = df1['구분']
df3 = df1['총계']
df_3years = pd.DataFrame([], columns=['구별', 'CCTV댓수', '최근증가율'])
df_3years['구별'] = df2
df_3years['CCTV댓수'] = df3

rate = pd.Series()
rate3 = pd.Series()

for i in range(0,25):
    temp = 0
    for j in range(1,4):
        temp += df1.iloc[i][-j]
    rate[i] = df1.iloc[i][1] - temp
    rate3[i] = temp

result = rate3 / rate * 100

for i in range(25): 
    df_3years['최근증가율'][i+1] = result[i].round(2)

df_3years

      구별  CCTV댓수   최근증가율
1    종로구    1980   46.23
2    중 구    2584   53.54
3    용산구    2847   93.94
4    성동구    4047   36.58
5    광진구    3480   46.53
6   동대문구    2759   34.19
7    중랑구    4193   73.55
8    성북구    4842   25.96
9    강북구    3321  100.42
10   도봉구    2247  155.92
11   노원구    2617   40.85
12   은평구    4653   37.99
13  서대문구    3445   58.68
14   마포구    2628   29.08
15   양천구    3851   36.13
16   강서구    3265   70.76
17   구로구    4693   50.66
18   금천구    2636   60.83
19  영등포구    4553   81.54
20   동작구    2671   44.07
21   관악구    5398   26.12
22   서초구    4995   59.53
23   강남구    7243   35.69
24   송파구    3203   28.79
25   강동구    3190   74.79

2. 서울시 인구 데이터를 다음과 같이 만들어 pop.csv 파일에 저장하세요.

In [88]:
pp = pd.read_csv('../data/서울시인구.txt', sep='\t', thousands=',')
pp.head()

,기간,자치구,세대,인구,인구.1,인구.2,인구.3,인구.4,인구.5,인구.6,인구.7,인구.8,세대당인구,65세이상고령자
0,기간,자치구,세대,합계,합계,합계,한국인,한국인,한국인,등록외국인,등록외국인,등록외국인,세대당인구,65세이상고령자
1,기간,자치구,세대,계,남자,여자,계,남자,여자,계,남자,여자,세대당인구,65세이상고령자
2,2021,합계,"4,426,007","9,736,027","4,721,977","5,014,050","9,509,458","4,618,040","4,891,418","226,569","103,937","122,632",2.15,"1,605,416"
3,2021,종로구,"73,494","153,789","74,186","79,603","144,683","70,183","74,500","9,106","4,003","5,103",1.97,"27,818"
4,2021,중구,"63,519","131,787","64,083","67,704","122,499","59,630","62,869","9,288","4,453","4,835",1.93,"24,392"

In [99]:
for i in range(len(pp.columns)):
    for j in pp.index:
        pp.iloc[j][i] = pp.iloc[j][i].replace(',', '')
pp.head()

,기간,자치구,세대,인구,인구.1,인구.2,인구.3,인구.4,인구.5,인구.6,인구.7,인구.8,세대당인구,65세이상고령자
0,기간,자치구,세대,합계,합계,합계,한국인,한국인,한국인,등록외국인,등록외국인,등록외국인,세대당인구,65세이상고령자
1,기간,자치구,세대,계,남자,여자,계,남자,여자,계,남자,여자,세대당인구,65세이상고령자
2,2021,합계,4426007,9736027,4721977,5014050,9509458,4618040,4891418,226569,103937,122632,2.15,1605416
3,2021,종로구,73494,153789,74186,79603,144683,70183,74500,9106,4003,5103,1.97,27818
4,2021,중구,63519,131787,64083,67704,122499,59630,62869,9288,4453,4835,1.93,24392

In [105]:
pp1 = pd.DataFrame([], columns=['구별', '인구수', '내국인', '외국인', '고령자', '외국인비율', '고령자비율'])

temp = []
for i in pp.index[3:]:
    temp.append(pp.iloc[i][1])
pp1['구별'] = temp

temp = []
for i in pp.index[3:]:
    temp.append(int(pp.iloc[i][3]))
pp1['인구수'] = temp

temp = []
for i in pp.index[3:]:
    temp.append(int(pp.iloc[i][6]))
pp1['내국인'] = temp

temp = []
for i in pp.index[3:]:
    temp.append(int(pp.iloc[i][9]))
pp1['외국인'] = temp

temp = []
for i in pp.index[3:]:
    temp.append(int(pp.iloc[i][13]))
pp1['고령자'] = temp

pp1['외국인비율'] = (pp1['외국인'] / pp1['인구수'] * 100).round(2)

pp1['고령자비율'] = (pp1['고령자'] / pp1['인구수'] * 100).round(2)

pp1

      구별     인구수     내국인    외국인    고령자  외국인비율  고령자비율
0    종로구  153789  144683   9106  27818   5.92  18.09
1     중구  131787  122499   9288  24392   7.05  18.51
2    용산구  237285  222953  14332  39070   6.04  16.47
3    성동구  292672  285990   6682  46380   2.28  15.85
4    광진구  352627  339996  12631  51723   3.58  14.67
5   동대문구  352006  337400  14606  62211   4.15  17.67
6    중랑구  391885  387350   4535  71682   1.16  18.29
7    성북구  440142  430528   9614  74709   2.18  16.97
8    강북구  302563  299182   3381  64333   1.12  21.26
9    도봉구  319373  317366   2007  64160   0.63  20.09
10   노원구  514946  510956   3990  88345   0.77  17.16
11   은평구  477173  473307   3866  87241   0.81  18.28
12  서대문구  315659  304819  10840  54268   3.43  17.19
13   마포구  378686  368905   9781  54582   2.58  14.41
14   양천구  450487  447302   3185  68627   0.71  15.23
15   강서구  579768  574315   5453  92558   0.94  15.96
16   구로구  421163  396754  24409  72611   5.80  17.24
17   금천구  244891  230811  14080  41041   5.75  16.76
18  영등포구  400908  376837  24071  62516   6.00  15.59
19   동작구  394364  385483   8881  66613   2.25  16.89
20   관악구  499449  485699  13750  79871   2.75  15.99
21   서초구  416167  412279   3888  60678   0.93  14.58
22   강남구  537800  533042   4758  78226   0.88  14.55
23   송파구  663965  658338   5627  97691   0.85  14.71
24   강동구  466472  462664   3808  74070   0.82  15.88